### ISSUE TITLE
Upgrade Vulnerable Libraries

### ISSUE THREAD

**Issue by biljanaLukovic** [trustbloc/vcs#1033]
Vulnerability : severity medium, type open redirect was identified in:
github.com/trustbloc/vcs/pkg/doc/vc@#5b36c4bfb27a, github.com/trustbloc/vcs/pkg/doc/vc/crypto@#5b36c4bfb27a and others
Fixed in: github.com/labstack/echo/v4@4.9.0
Expected action: upgrade to the latest version of vulnerable library

Vulnerability: severity medium, type denial of service was identified in: golang.org/x/net/http2

Introduced through
github.com/trustbloc/vcs/pkg/profile@#5b36c4bfb27a, github.com/trustbloc/vcs/pkg/doc/vc@#5b36c4bfb27a and others
Fixed in: golang.org/x/net/http2@0.4.0
Expected action: upgrade to the latest/suggested version of vulnerable library

**Comment by sandrask** [comment]
No longer an issue
