### ISSUE TITLE
Add  default http timeout to proxy

### ISSUE THREAD

**Issue by sandrask** [trustbloc/vcs#391]
Currently our http clients don't have timeout which might be an issue especially for proxy which is connecting to uni-resolver.  I observed  that request to sov was hanging in CI this morning.

Add default top level client timeout (defaulted to 60s).

Created #392 for @troyronda comment bellow.

**Comment by troyronda** [comment]
This is good.

It would also be useful to have an additional configuration in the config.json for each pattern to be able to override the default.
