### ISSUE TITLE
cleanup issuer/verifier profile creation options and work arounds

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/vcs#741]
Currently we have some work arounds or customization for applying custom settings to profile creation.
Either they should be removed or should be done in better way.

For Example in issuer some of the profile options are for supporting custom settings which are no longer required https://github.com/trustbloc/vcs/blob/43a768b1161a87ebe0db90cacd64cae14bab681a/pkg/restapi/issuer/operation/models.go#L49-L75

**Comment by rolsonquadras** [comment]
This will be refactored as part of https://github.com/trustbloc/vcs/issues/752and https://github.com/trustbloc/vcs/issues/753
