### ISSUE TITLE
Add dependencybot to update go.mod

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/vcs#763]
The TrustBloc VCS uses [Hyperledger Aries Framework Go](https://github.com/hyperledger/aries-framework-go/) as a library for VC related operations. The AFG is under active development, and usually, changes affect VCS build. Currently, the team updates the dependency version manually. We should explore the option to add dependencybot to update the version.

Reference from TrustBloc Wallet repo https://github.com/trustbloc/wallet/blob/main/.github/dependabot.yml#L60

**Comment by birtony** [comment]
@vkubiv you can use [the official Dependabot documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) as a reference as well

**Comment by vkubiv** [comment]
Dependency bot creating pull requests separately for each go.mod file. But this will not work for vcs project, just updating root go.mod without updating at same time cmd and bdd will fail PR checks.
