### ISSUE TITLE
API to generate Well Known DID Configuration

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/vcs#839]
- API Definition
  - HTTP GET /<verifier|issuer>/profiles/{profileID}/well-known/did-config) 
  - Response - VC in JWT/JSON-LD format
- Logic
  - Fetch the profile data from profileID
  - Create a VC with 
    - credentialSubject.id = signingDID from profile
    - origin = url from profile
  - Sign VC (based on vc-type from profile)

Sample VC https://identity.foundation/.well-known/resources/did-configuration/#linked-data-proof-format

**Comment by fqutishat** [comment]
Add dev mode flag if dev mode true enable endpoint
